/**
 * Autogenerated by Thrift Compiler (0.14.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef LIMITS_TYPES_H
#define LIMITS_TYPES_H

/* base includes */
#include <glib-object.h>
#include <thrift/c_glib/thrift_struct.h>
#include <thrift/c_glib/protocol/thrift_protocol.h>
/* custom thrift includes */

/* begin types */

/* constants */
#define EDAM_ATTRIBUTE_LEN_MIN 1
#define EDAM_ATTRIBUTE_LEN_MAX 4096
#define EDAM_ATTRIBUTE_REGEX g_strdup ("^[^\p{Cc}\p{Zl}\p{Zp}]{1,4096}$")
#define EDAM_ATTRIBUTE_LIST_MAX 100
#define EDAM_ATTRIBUTE_MAP_MAX 100
#define EDAM_GUID_LEN_MIN 36
#define EDAM_GUID_LEN_MAX 36
#define EDAM_GUID_REGEX g_strdup ("^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$")
#define EDAM_EMAIL_LEN_MIN 6
#define EDAM_EMAIL_LEN_MAX 255
#define EDAM_EMAIL_LOCAL_REGEX g_strdup ("^[A-Za-z0-9!#$%&'*+/=?^_`{|}~-]+(\.[A-Za-z0-9!#$%&'*+/=?^_`{|}~-]+)*$")
#define EDAM_EMAIL_DOMAIN_REGEX g_strdup ("^[A-Za-z0-9-]*[A-Za-z0-9](\.[A-Za-z0-9-]*[A-Za-z0-9])*\.([A-Za-z]{2,})$")
#define EDAM_EMAIL_REGEX g_strdup ("^[A-Za-z0-9!#$%&'*+/=?^_`{|}~-]+(\.[A-Za-z0-9!#$%&'*+/=?^_`{|}~-]+)*@[A-Za-z0-9-]*[A-Za-z0-9](\.[A-Za-z0-9-]*[A-Za-z0-9])*\.([A-Za-z]{2,})$")
#define EDAM_VAT_REGEX g_strdup ("^(AT)?U[0-9]{8}$|^(BE)?0?[0-9]{9}$|^(BG)?[0-9]{9,10}$|^(CY)?[0-9]{8}L$|^(CZ)?[0-9]{8,10}$|^(DE)?[0-9]{9}$|^(DK)?[0-9]{8}$|^(EE)?[0-9]{9}$|^(EL|GR)?[0-9]{9}$|^(ES)?[0-9A-Z][0-9]{7}[0-9A-Z]$|^(FI)?[0-9]{8}$|^(FR)?[0-9A-Z]{2}[0-9]{9}$|^(GB)?([0-9]{9}([0-9]{3})?|[A-Z]{2}[0-9]{3})$|^(HU)?[0-9]{8}$|^(IE)?[0-9]{7}[A-Z]{1,2}$|^(IT)?[0-9]{11}$|^(LT)?([0-9]{9}|[0-9]{12})$|^(LU)?[0-9]{8}$|^(LV)?[0-9]{11}$|^(MT)?[0-9]{8}$|^(NL)?[0-9]{9}B[0-9]{2}$|^(PL)?[0-9]{10}$|^(PT)?[0-9]{9}$|^(RO)?[0-9]{2,10}$|^(SE)?[0-9]{12}$|^(SI)?[0-9]{8}$|^(SK)?[0-9]{10}$|^[0-9]{9}MVA$|^[0-9]{6}$|^CHE[0-9]{9}(TVA|MWST|IVA)$")
#define EDAM_TIMEZONE_LEN_MIN 1
#define EDAM_TIMEZONE_LEN_MAX 32
#define EDAM_TIMEZONE_REGEX g_strdup ("^([A-Za-z_-]+(/[A-Za-z_-]+)*)|(GMT(-|\+)[0-9]{1,2}(:[0-9]{2})?)$")
#define EDAM_MIME_LEN_MIN 3
#define EDAM_MIME_LEN_MAX 255
#define EDAM_MIME_REGEX g_strdup ("^[A-Za-z]+/[A-Za-z0-9._+-]+$")
#define EDAM_MIME_TYPE_GIF g_strdup ("image/gif")
#define EDAM_MIME_TYPE_JPEG g_strdup ("image/jpeg")
#define EDAM_MIME_TYPE_PNG g_strdup ("image/png")
#define EDAM_MIME_TYPE_TIFF g_strdup ("image/tiff")
#define EDAM_MIME_TYPE_BMP g_strdup ("image/bmp")
#define EDAM_MIME_TYPE_WAV g_strdup ("audio/wav")
#define EDAM_MIME_TYPE_MP3 g_strdup ("audio/mpeg")
#define EDAM_MIME_TYPE_AMR g_strdup ("audio/amr")
#define EDAM_MIME_TYPE_AAC g_strdup ("audio/aac")
#define EDAM_MIME_TYPE_M4A g_strdup ("audio/mp4")
#define EDAM_MIME_TYPE_MP4_VIDEO g_strdup ("video/mp4")
#define EDAM_MIME_TYPE_INK g_strdup ("application/vnd.evernote.ink")
#define EDAM_MIME_TYPE_PDF g_strdup ("application/pdf")
#define EDAM_MIME_TYPE_DEFAULT g_strdup ("application/octet-stream")
GHashTable *edam_mime_types_constant();
#define EDAM_MIME_TYPES (edam_mime_types_constant())
GHashTable *edam_indexable_resource_mime_types_constant();
#define EDAM_INDEXABLE_RESOURCE_MIME_TYPES (edam_indexable_resource_mime_types_constant())
GHashTable *edam_indexable_plaintext_mime_types_constant();
#define EDAM_INDEXABLE_PLAINTEXT_MIME_TYPES (edam_indexable_plaintext_mime_types_constant())
#define EDAM_SEARCH_QUERY_LEN_MIN 0
#define EDAM_SEARCH_QUERY_LEN_MAX 1024
#define EDAM_SEARCH_QUERY_REGEX g_strdup ("^[^\p{Cc}\p{Zl}\p{Zp}]{0,1024}$")
#define EDAM_HASH_LEN 16
#define EDAM_USER_USERNAME_LEN_MIN 1
#define EDAM_USER_USERNAME_LEN_MAX 64
#define EDAM_USER_USERNAME_REGEX g_strdup ("^[a-z0-9]([a-z0-9_-]{0,62}[a-z0-9])?$")
#define EDAM_USER_NAME_LEN_MIN 1
#define EDAM_USER_NAME_LEN_MAX 255
#define EDAM_USER_NAME_REGEX g_strdup ("^[^\p{Cc}\p{Zl}\p{Zp}]{1,255}$")
#define EDAM_TAG_NAME_LEN_MIN 1
#define EDAM_TAG_NAME_LEN_MAX 100
#define EDAM_TAG_NAME_REGEX g_strdup ("^[^,\p{Cc}\p{Z}]([^,\p{Cc}\p{Zl}\p{Zp}]{0,98}[^,\p{Cc}\p{Z}])?$")
#define EDAM_NOTE_TITLE_LEN_MIN 1
#define EDAM_NOTE_TITLE_LEN_MAX 255
#define EDAM_NOTE_TITLE_REGEX g_strdup ("^[^\p{Cc}\p{Z}]([^\p{Cc}\p{Zl}\p{Zp}]{0,253}[^\p{Cc}\p{Z}])?$")
#define EDAM_NOTE_CONTENT_LEN_MIN 0
#define EDAM_NOTE_CONTENT_LEN_MAX 5242880
#define EDAM_APPLICATIONDATA_NAME_LEN_MIN 3
#define EDAM_APPLICATIONDATA_NAME_LEN_MAX 32
#define EDAM_APPLICATIONDATA_VALUE_LEN_MIN 0
#define EDAM_APPLICATIONDATA_VALUE_LEN_MAX 4092
#define EDAM_APPLICATIONDATA_ENTRY_LEN_MAX 4095
#define EDAM_APPLICATIONDATA_NAME_REGEX g_strdup ("^[A-Za-z0-9_.-]{3,32}$")
#define EDAM_APPLICATIONDATA_VALUE_REGEX g_strdup ("^[\p{Space}[^\p{Cc}]]{0,4092}$")
#define EDAM_NOTEBOOK_NAME_LEN_MIN 1
#define EDAM_NOTEBOOK_NAME_LEN_MAX 100
#define EDAM_NOTEBOOK_NAME_REGEX g_strdup ("^[^\p{Cc}\p{Z}]([^\p{Cc}\p{Zl}\p{Zp}]{0,98}[^\p{Cc}\p{Z}])?$")
#define EDAM_NOTEBOOK_STACK_LEN_MIN 1
#define EDAM_NOTEBOOK_STACK_LEN_MAX 100
#define EDAM_NOTEBOOK_STACK_REGEX g_strdup ("^[^\p{Cc}\p{Z}]([^\p{Cc}\p{Zl}\p{Zp}]{0,98}[^\p{Cc}\p{Z}])?$")
#define EDAM_WORKSPACE_NAME_LEN_MIN 1
#define EDAM_WORKSPACE_NAME_LEN_MAX 100
#define EDAM_WORKSPACE_DESCRIPTION_LEN_MAX 600
#define EDAM_WORKSPACE_NAME_REGEX g_strdup ("^[^\p{Cc}\p{Z}]([^\p{Cc}\p{Zl}\p{Zp}]{0,98}[^\p{Cc}\p{Z}])?$")
#define EDAM_PUBLISHING_URI_LEN_MIN 1
#define EDAM_PUBLISHING_URI_LEN_MAX 255
#define EDAM_PUBLISHING_URI_REGEX g_strdup ("^[a-zA-Z0-9.~_+-]{1,255}$")
GHashTable *edam_publishing_uri_prohibited_constant();
#define EDAM_PUBLISHING_URI_PROHIBITED (edam_publishing_uri_prohibited_constant())
#define EDAM_PUBLISHING_DESCRIPTION_LEN_MIN 1
#define EDAM_PUBLISHING_DESCRIPTION_LEN_MAX 200
#define EDAM_PUBLISHING_DESCRIPTION_REGEX g_strdup ("^[^\p{Cc}\p{Z}]([^\p{Cc}\p{Zl}\p{Zp}]{0,198}[^\p{Cc}\p{Z}])?$")
#define EDAM_SAVED_SEARCH_NAME_LEN_MIN 1
#define EDAM_SAVED_SEARCH_NAME_LEN_MAX 100
#define EDAM_SAVED_SEARCH_NAME_REGEX g_strdup ("^[^\p{Cc}\p{Z}]([^\p{Cc}\p{Zl}\p{Zp}]{0,98}[^\p{Cc}\p{Z}])?$")
#define EDAM_USER_PASSWORD_LEN_MIN 6
#define EDAM_USER_PASSWORD_LEN_MAX 64
#define EDAM_USER_PASSWORD_REGEX g_strdup ("^[A-Za-z0-9!#$%&'()*+,./:;<=>?@^_`{|}~\[\]\\-]{6,64}$")
#define EDAM_BUSINESS_URI_LEN_MAX 32
#define EDAM_BUSINESS_MARKETING_CODE_REGEX_PATTERN g_strdup ("[A-Za-z0-9-]{1,128}")
#define EDAM_NOTE_TAGS_MAX 100
#define EDAM_NOTE_RESOURCES_MAX 1000
#define EDAM_USER_TAGS_MAX 100000
#define EDAM_BUSINESS_TAGS_MAX 100000
#define EDAM_USER_SAVED_SEARCHES_MAX 100
#define EDAM_USER_NOTES_MAX 100000
#define EDAM_BUSINESS_NOTES_MAX 500000
#define EDAM_USER_NOTEBOOKS_MAX 250
#define EDAM_USER_WORKSPACES_MAX 0
#define EDAM_BUSINESS_NOTEBOOKS_MAX 10000
#define EDAM_BUSINESS_WORKSPACES_MAX 1000
#define EDAM_USER_RECENT_MAILED_ADDRESSES_MAX 10
#define EDAM_USER_MAIL_LIMIT_DAILY_FREE 50
#define EDAM_USER_MAIL_LIMIT_DAILY_PREMIUM 200
#define EDAM_USER_UPLOAD_LIMIT_FREE G_GINT64_CONSTANT (62914560)
#define EDAM_USER_UPLOAD_LIMIT_PREMIUM G_GINT64_CONSTANT (10737418240)
#define EDAM_USER_UPLOAD_LIMIT_BUSINESS_FIRST_MONTH G_GINT64_CONSTANT (53687091200)
#define EDAM_USER_UPLOAD_LIMIT_BUSINESS_NEXT_MONTH G_GINT64_CONSTANT (21474836480)
#define EDAM_USER_UPLOAD_LIMIT_PLUS G_GINT64_CONSTANT (1073741824)
#define EDAM_USER_UPLOAD_SURVEY_THRESHOLD G_GINT64_CONSTANT (5368709120)
#define EDAM_USER_UPLOAD_LIMIT_BUSINESS G_GINT64_CONSTANT (10737418240)
#define EDAM_USER_UPLOAD_LIMIT_BUSINESS_PER_USER G_GINT64_CONSTANT (2147483647)
#define EDAM_NOTE_SIZE_MAX_FREE 26214400
#define EDAM_NOTE_SIZE_MAX_PREMIUM 209715200
#define EDAM_RESOURCE_SIZE_MAX_FREE 26214400
#define EDAM_RESOURCE_SIZE_MAX_PREMIUM 209715200
#define EDAM_USER_LINKED_NOTEBOOK_MAX 100
#define EDAM_USER_LINKED_NOTEBOOK_MAX_PREMIUM 500
#define EDAM_NOTEBOOK_BUSINESS_SHARED_NOTEBOOK_MAX 5000
#define EDAM_NOTEBOOK_PERSONAL_SHARED_NOTEBOOK_MAX 500
#define EDAM_NOTE_BUSINESS_SHARED_NOTE_MAX 1000
#define EDAM_NOTE_PERSONAL_SHARED_NOTE_MAX 100
#define EDAM_NOTE_CONTENT_CLASS_LEN_MIN 3
#define EDAM_NOTE_CONTENT_CLASS_LEN_MAX 32
#define EDAM_NOTE_CONTENT_CLASS_REGEX g_strdup ("^[A-Za-z0-9_.-]{3,32}$")
#define EDAM_HELLO_APP_CONTENT_CLASS_PREFIX g_strdup ("evernote.hello.")
#define EDAM_FOOD_APP_CONTENT_CLASS_PREFIX g_strdup ("evernote.food.")
#define EDAM_CONTENT_CLASS_HELLO_ENCOUNTER g_strdup ("evernote.hello.encounter")
#define EDAM_CONTENT_CLASS_HELLO_PROFILE g_strdup ("evernote.hello.profile")
#define EDAM_CONTENT_CLASS_FOOD_MEAL g_strdup ("evernote.food.meal")
#define EDAM_CONTENT_CLASS_SKITCH_PREFIX g_strdup ("evernote.skitch")
#define EDAM_CONTENT_CLASS_SKITCH g_strdup ("evernote.skitch")
#define EDAM_CONTENT_CLASS_SKITCH_PDF g_strdup ("evernote.skitch.pdf")
#define EDAM_CONTENT_CLASS_PENULTIMATE_PREFIX g_strdup ("evernote.penultimate.")
#define EDAM_CONTENT_CLASS_PENULTIMATE_NOTEBOOK g_strdup ("evernote.penultimate.notebook")
#define EDAM_SOURCE_APPLICATION_POSTIT g_strdup ("postit")
#define EDAM_SOURCE_APPLICATION_MOLESKINE g_strdup ("moleskine")
#define EDAM_SOURCE_APPLICATION_EN_SCANSNAP g_strdup ("scanner.scansnap.evernote")
#define EDAM_SOURCE_APPLICATION_EWC g_strdup ("clipncite.web")
#define EDAM_SOURCE_APPLICATION_ANDROID_SHARE_EXTENSION g_strdup ("android.clipper.evernote")
#define EDAM_SOURCE_APPLICATION_IOS_SHARE_EXTENSION g_strdup ("ios.clipper.evernote")
#define EDAM_SOURCE_APPLICATION_WEB_CLIPPER g_strdup ("webclipper.evernote")
#define EDAM_SOURCE_OUTLOOK_CLIPPER g_strdup ("app.ms.outlook")
#define EDAM_NOTE_TITLE_QUALITY_UNTITLED 0
#define EDAM_NOTE_TITLE_QUALITY_LOW 1
#define EDAM_NOTE_TITLE_QUALITY_MEDIUM 2
#define EDAM_NOTE_TITLE_QUALITY_HIGH 3
#define EDAM_RELATED_PLAINTEXT_LEN_MIN 1
#define EDAM_RELATED_PLAINTEXT_LEN_MAX 131072
#define EDAM_RELATED_MAX_NOTES 25
#define EDAM_RELATED_MAX_NOTEBOOKS 1
#define EDAM_RELATED_MAX_TAGS 25
#define EDAM_RELATED_MAX_EXPERTS 10
#define EDAM_RELATED_MAX_RELATED_CONTENT 10
#define EDAM_BUSINESS_NOTEBOOK_DESCRIPTION_LEN_MIN 1
#define EDAM_BUSINESS_NOTEBOOK_DESCRIPTION_LEN_MAX 200
#define EDAM_BUSINESS_NOTEBOOK_DESCRIPTION_REGEX g_strdup ("^[^\p{Cc}\p{Z}]([^\p{Cc}\p{Zl}\p{Zp}]{0,198}[^\p{Cc}\p{Z}])?$")
#define EDAM_BUSINESS_PHONE_NUMBER_LEN_MAX 20
#define EDAM_PREFERENCE_NAME_LEN_MIN 3
#define EDAM_PREFERENCE_NAME_LEN_MAX 32
#define EDAM_PREFERENCE_VALUE_LEN_MIN 1
#define EDAM_PREFERENCE_VALUE_LEN_MAX 1024
#define EDAM_MAX_PREFERENCES 100
#define EDAM_MAX_VALUES_PER_PREFERENCE 256
#define EDAM_PREFERENCE_ONLY_ONE_VALUE_LEN_MAX 16384
#define EDAM_PREFERENCE_NAME_REGEX g_strdup ("^[A-Za-z0-9_.-]{3,32}$")
#define EDAM_PREFERENCE_VALUE_REGEX g_strdup ("^[^\p{Cc}]{1,1024}$")
#define EDAM_PREFERENCE_ONLY_ONE_VALUE_REGEX g_strdup ("^[^\p{Cc}]{1,16384}$")
#define EDAM_PREFERENCE_SHORTCUTS g_strdup ("evernote.shortcuts")
#define EDAM_PREFERENCE_BUSINESS_DEFAULT_NOTEBOOK g_strdup ("evernote.business.notebook")
#define EDAM_PREFERENCE_BUSINESS_QUICKNOTE g_strdup ("evernote.business.quicknote")
#define EDAM_PREFERENCE_SHORTCUTS_MAX_VALUES 250
#define EDAM_DEVICE_ID_LEN_MAX 32
#define EDAM_DEVICE_ID_REGEX g_strdup ("^[^\p{Cc}]{1,32}$")
#define EDAM_DEVICE_DESCRIPTION_LEN_MAX 64
#define EDAM_DEVICE_DESCRIPTION_REGEX g_strdup ("^[^\p{Cc}]{1,64}$")
#define EDAM_SEARCH_SUGGESTIONS_MAX 10
#define EDAM_SEARCH_SUGGESTIONS_PREFIX_LEN_MAX 1024
#define EDAM_SEARCH_SUGGESTIONS_PREFIX_LEN_MIN 2
#define EDAM_FIND_CONTACT_DEFAULT_MAX_RESULTS 100
#define EDAM_FIND_CONTACT_MAX_RESULTS 256
#define EDAM_NOTE_LOCK_VIEWERS_NOTES_MAX 150
#define EDAM_GET_ORDERS_MAX_RESULTS 2000
#define EDAM_MESSAGE_BODY_LEN_MAX 2048
#define EDAM_MESSAGE_BODY_REGEX g_strdup ("^[^\p{Cc}\p{Z}]([^\p{Cc}\p{Zl}\p{Zp}]{0,2046}[^\p{Cc}\p{Z}])?$")
#define EDAM_MESSAGE_RECIPIENTS_MAX 50
#define EDAM_MESSAGE_ATTACHMENTS_MAX 100
#define EDAM_MESSAGE_ATTACHMENT_TITLE_LEN_MAX 255
#define EDAM_MESSAGE_ATTACHMENT_TITLE_REGEX g_strdup ("^[^\p{Cc}\p{Z}]([^\p{Cc}\p{Zl}\p{Zp}]{0,253}[^\p{Cc}\p{Z}])?$")
#define EDAM_MESSAGE_ATTACHMENT_SNIPPET_LEN_MAX 2048
#define EDAM_MESSAGE_ATTACHMENT_SNIPPET_REGEX g_strdup ("^[^\p{Cc}\p{Z}]([\n[^\p{Cc}\p{Zl}\p{Zp}]]{0,2046}[^\p{Cc}\p{Z}])?$")
#define EDAM_USER_PROFILE_PHOTO_MAX_BYTES 716800
#define EDAM_PROMOTION_ID_LEN_MAX 32
#define EDAM_PROMOTION_ID_REGEX g_strdup ("^[A-Za-z0-9_.-]{1,32}$")
#define EDAM_APP_RATING_MIN 1
#define EDAM_APP_RATING_MAX 5
#define EDAM_SNIPPETS_NOTES_MAX 24
#define EDAM_CONNECTED_IDENTITY_REQUEST_MAX 100
#define EDAM_OPEN_ID_ACCESS_TOKEN_MAX 1000

#endif /* LIMITS_TYPES_H */
