/**
 * Autogenerated by Thrift Compiler (0.14.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef USER_STORE_TYPES_H
#define USER_STORE_TYPES_H

/* base includes */
#include <glib-object.h>
#include <thrift/c_glib/thrift_struct.h>
#include <thrift/c_glib/protocol/thrift_protocol.h>
/* other thrift includes */
#include "types_types.h"
#include "errors_types.h"

/* custom thrift includes */

/* begin types */

/* struct PublicUserInfo */
struct _PublicUserInfo
{ 
  ThriftStruct parent; 

  /* public */
  gint32 userId;
  ServiceLevel serviceLevel;
  gboolean __isset_serviceLevel;
  gchar * username;
  gboolean __isset_username;
  gchar * noteStoreUrl;
  gboolean __isset_noteStoreUrl;
  gchar * webApiUrlPrefix;
  gboolean __isset_webApiUrlPrefix;
};
typedef struct _PublicUserInfo PublicUserInfo;

struct _PublicUserInfoClass
{
  ThriftStructClass parent;
};
typedef struct _PublicUserInfoClass PublicUserInfoClass;

GType public_user_info_get_type (void);
#define TYPE_PUBLIC_USER_INFO (public_user_info_get_type())
#define PUBLIC_USER_INFO(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_PUBLIC_USER_INFO, PublicUserInfo))
#define PUBLIC_USER_INFO_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_PUBLIC_USER_INFO, PublicUserInfoClass))
#define IS_PUBLIC_USER_INFO(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_PUBLIC_USER_INFO))
#define IS_PUBLIC_USER_INFO_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_PUBLIC_USER_INFO))
#define PUBLIC_USER_INFO_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_PUBLIC_USER_INFO, PublicUserInfoClass))

/* struct UserUrls */
struct _UserUrls
{ 
  ThriftStruct parent; 

  /* public */
  gchar * noteStoreUrl;
  gboolean __isset_noteStoreUrl;
  gchar * webApiUrlPrefix;
  gboolean __isset_webApiUrlPrefix;
  gchar * userStoreUrl;
  gboolean __isset_userStoreUrl;
  gchar * utilityUrl;
  gboolean __isset_utilityUrl;
  gchar * messageStoreUrl;
  gboolean __isset_messageStoreUrl;
  gchar * userWebSocketUrl;
  gboolean __isset_userWebSocketUrl;
};
typedef struct _UserUrls UserUrls;

struct _UserUrlsClass
{
  ThriftStructClass parent;
};
typedef struct _UserUrlsClass UserUrlsClass;

GType user_urls_get_type (void);
#define TYPE_USER_URLS (user_urls_get_type())
#define USER_URLS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_USER_URLS, UserUrls))
#define USER_URLS_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_USER_URLS, UserUrlsClass))
#define IS_USER_URLS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_USER_URLS))
#define IS_USER_URLS_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_USER_URLS))
#define USER_URLS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_USER_URLS, UserUrlsClass))

/* struct AuthenticationResult */
struct _AuthenticationResult
{ 
  ThriftStruct parent; 

  /* public */
  gint64 currentTime;
  gchar * authenticationToken;
  gint64 expiration;
  User * user;
  gboolean __isset_user;
  PublicUserInfo * publicUserInfo;
  gboolean __isset_publicUserInfo;
  gchar * noteStoreUrl;
  gboolean __isset_noteStoreUrl;
  gchar * webApiUrlPrefix;
  gboolean __isset_webApiUrlPrefix;
  gboolean secondFactorRequired;
  gboolean __isset_secondFactorRequired;
  gchar * secondFactorDeliveryHint;
  gboolean __isset_secondFactorDeliveryHint;
  UserUrls * urls;
  gboolean __isset_urls;
};
typedef struct _AuthenticationResult AuthenticationResult;

struct _AuthenticationResultClass
{
  ThriftStructClass parent;
};
typedef struct _AuthenticationResultClass AuthenticationResultClass;

GType authentication_result_get_type (void);
#define TYPE_AUTHENTICATION_RESULT (authentication_result_get_type())
#define AUTHENTICATION_RESULT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_AUTHENTICATION_RESULT, AuthenticationResult))
#define AUTHENTICATION_RESULT_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_AUTHENTICATION_RESULT, AuthenticationResultClass))
#define IS_AUTHENTICATION_RESULT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_AUTHENTICATION_RESULT))
#define IS_AUTHENTICATION_RESULT_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_AUTHENTICATION_RESULT))
#define AUTHENTICATION_RESULT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_AUTHENTICATION_RESULT, AuthenticationResultClass))

/* struct BootstrapSettings */
struct _BootstrapSettings
{ 
  ThriftStruct parent; 

  /* public */
  gchar * serviceHost;
  gchar * marketingUrl;
  gchar * supportUrl;
  gchar * accountEmailDomain;
  gboolean enableFacebookSharing;
  gboolean __isset_enableFacebookSharing;
  gboolean enableGiftSubscriptions;
  gboolean __isset_enableGiftSubscriptions;
  gboolean enableSupportTickets;
  gboolean __isset_enableSupportTickets;
  gboolean enableSharedNotebooks;
  gboolean __isset_enableSharedNotebooks;
  gboolean enableSingleNoteSharing;
  gboolean __isset_enableSingleNoteSharing;
  gboolean enableSponsoredAccounts;
  gboolean __isset_enableSponsoredAccounts;
  gboolean enableTwitterSharing;
  gboolean __isset_enableTwitterSharing;
  gboolean enableLinkedInSharing;
  gboolean __isset_enableLinkedInSharing;
  gboolean enablePublicNotebooks;
  gboolean __isset_enablePublicNotebooks;
  gboolean enableGoogle;
  gboolean __isset_enableGoogle;
};
typedef struct _BootstrapSettings BootstrapSettings;

struct _BootstrapSettingsClass
{
  ThriftStructClass parent;
};
typedef struct _BootstrapSettingsClass BootstrapSettingsClass;

GType bootstrap_settings_get_type (void);
#define TYPE_BOOTSTRAP_SETTINGS (bootstrap_settings_get_type())
#define BOOTSTRAP_SETTINGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_BOOTSTRAP_SETTINGS, BootstrapSettings))
#define BOOTSTRAP_SETTINGS_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_BOOTSTRAP_SETTINGS, BootstrapSettingsClass))
#define IS_BOOTSTRAP_SETTINGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_BOOTSTRAP_SETTINGS))
#define IS_BOOTSTRAP_SETTINGS_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_BOOTSTRAP_SETTINGS))
#define BOOTSTRAP_SETTINGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_BOOTSTRAP_SETTINGS, BootstrapSettingsClass))

/* struct BootstrapProfile */
struct _BootstrapProfile
{ 
  ThriftStruct parent; 

  /* public */
  gchar * name;
  BootstrapSettings * settings;
};
typedef struct _BootstrapProfile BootstrapProfile;

struct _BootstrapProfileClass
{
  ThriftStructClass parent;
};
typedef struct _BootstrapProfileClass BootstrapProfileClass;

GType bootstrap_profile_get_type (void);
#define TYPE_BOOTSTRAP_PROFILE (bootstrap_profile_get_type())
#define BOOTSTRAP_PROFILE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_BOOTSTRAP_PROFILE, BootstrapProfile))
#define BOOTSTRAP_PROFILE_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_BOOTSTRAP_PROFILE, BootstrapProfileClass))
#define IS_BOOTSTRAP_PROFILE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_BOOTSTRAP_PROFILE))
#define IS_BOOTSTRAP_PROFILE_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_BOOTSTRAP_PROFILE))
#define BOOTSTRAP_PROFILE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_BOOTSTRAP_PROFILE, BootstrapProfileClass))

/* struct BootstrapInfo */
struct _BootstrapInfo
{ 
  ThriftStruct parent; 

  /* public */
  GPtrArray * profiles;
};
typedef struct _BootstrapInfo BootstrapInfo;

struct _BootstrapInfoClass
{
  ThriftStructClass parent;
};
typedef struct _BootstrapInfoClass BootstrapInfoClass;

GType bootstrap_info_get_type (void);
#define TYPE_BOOTSTRAP_INFO (bootstrap_info_get_type())
#define BOOTSTRAP_INFO(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_BOOTSTRAP_INFO, BootstrapInfo))
#define BOOTSTRAP_INFO_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_BOOTSTRAP_INFO, BootstrapInfoClass))
#define IS_BOOTSTRAP_INFO(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_BOOTSTRAP_INFO))
#define IS_BOOTSTRAP_INFO_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_BOOTSTRAP_INFO))
#define BOOTSTRAP_INFO_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_BOOTSTRAP_INFO, BootstrapInfoClass))

/* constants */
#define EDAM_VERSION_MAJOR 1
#define EDAM_VERSION_MINOR 28

/* struct UserStoreCheckVersionArgs */
struct _UserStoreCheckVersionArgs
{ 
  ThriftStruct parent; 

  /* public */
  gchar * clientName;
  gboolean __isset_clientName;
  gint16 edamVersionMajor;
  gboolean __isset_edamVersionMajor;
  gint16 edamVersionMinor;
  gboolean __isset_edamVersionMinor;
};
typedef struct _UserStoreCheckVersionArgs UserStoreCheckVersionArgs;

struct _UserStoreCheckVersionArgsClass
{
  ThriftStructClass parent;
};
typedef struct _UserStoreCheckVersionArgsClass UserStoreCheckVersionArgsClass;

GType user_store_check_version_args_get_type (void);
#define TYPE_USER_STORE_CHECK_VERSION_ARGS (user_store_check_version_args_get_type())
#define USER_STORE_CHECK_VERSION_ARGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_USER_STORE_CHECK_VERSION_ARGS, UserStoreCheckVersionArgs))
#define USER_STORE_CHECK_VERSION_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_USER_STORE_CHECK_VERSION_ARGS, UserStoreCheckVersionArgsClass))
#define IS_USER_STORE_CHECK_VERSION_ARGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_USER_STORE_CHECK_VERSION_ARGS))
#define IS_USER_STORE_CHECK_VERSION_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_USER_STORE_CHECK_VERSION_ARGS))
#define USER_STORE_CHECK_VERSION_ARGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_USER_STORE_CHECK_VERSION_ARGS, UserStoreCheckVersionArgsClass))

/* struct UserStoreCheckVersionResult */
struct _UserStoreCheckVersionResult
{ 
  ThriftStruct parent; 

  /* public */
  gboolean success;
  gboolean __isset_success;
};
typedef struct _UserStoreCheckVersionResult UserStoreCheckVersionResult;

struct _UserStoreCheckVersionResultClass
{
  ThriftStructClass parent;
};
typedef struct _UserStoreCheckVersionResultClass UserStoreCheckVersionResultClass;

GType user_store_check_version_result_get_type (void);
#define TYPE_USER_STORE_CHECK_VERSION_RESULT (user_store_check_version_result_get_type())
#define USER_STORE_CHECK_VERSION_RESULT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_USER_STORE_CHECK_VERSION_RESULT, UserStoreCheckVersionResult))
#define USER_STORE_CHECK_VERSION_RESULT_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_USER_STORE_CHECK_VERSION_RESULT, UserStoreCheckVersionResultClass))
#define IS_USER_STORE_CHECK_VERSION_RESULT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_USER_STORE_CHECK_VERSION_RESULT))
#define IS_USER_STORE_CHECK_VERSION_RESULT_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_USER_STORE_CHECK_VERSION_RESULT))
#define USER_STORE_CHECK_VERSION_RESULT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_USER_STORE_CHECK_VERSION_RESULT, UserStoreCheckVersionResultClass))

/* struct UserStoreGetBootstrapInfoArgs */
struct _UserStoreGetBootstrapInfoArgs
{ 
  ThriftStruct parent; 

  /* public */
  gchar * locale;
  gboolean __isset_locale;
};
typedef struct _UserStoreGetBootstrapInfoArgs UserStoreGetBootstrapInfoArgs;

struct _UserStoreGetBootstrapInfoArgsClass
{
  ThriftStructClass parent;
};
typedef struct _UserStoreGetBootstrapInfoArgsClass UserStoreGetBootstrapInfoArgsClass;

GType user_store_get_bootstrap_info_args_get_type (void);
#define TYPE_USER_STORE_GET_BOOTSTRAP_INFO_ARGS (user_store_get_bootstrap_info_args_get_type())
#define USER_STORE_GET_BOOTSTRAP_INFO_ARGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_USER_STORE_GET_BOOTSTRAP_INFO_ARGS, UserStoreGetBootstrapInfoArgs))
#define USER_STORE_GET_BOOTSTRAP_INFO_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_USER_STORE_GET_BOOTSTRAP_INFO_ARGS, UserStoreGetBootstrapInfoArgsClass))
#define IS_USER_STORE_GET_BOOTSTRAP_INFO_ARGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_USER_STORE_GET_BOOTSTRAP_INFO_ARGS))
#define IS_USER_STORE_GET_BOOTSTRAP_INFO_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_USER_STORE_GET_BOOTSTRAP_INFO_ARGS))
#define USER_STORE_GET_BOOTSTRAP_INFO_ARGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_USER_STORE_GET_BOOTSTRAP_INFO_ARGS, UserStoreGetBootstrapInfoArgsClass))

/* struct UserStoreGetBootstrapInfoResult */
struct _UserStoreGetBootstrapInfoResult
{ 
  ThriftStruct parent; 

  /* public */
  BootstrapInfo * success;
  gboolean __isset_success;
};
typedef struct _UserStoreGetBootstrapInfoResult UserStoreGetBootstrapInfoResult;

struct _UserStoreGetBootstrapInfoResultClass
{
  ThriftStructClass parent;
};
typedef struct _UserStoreGetBootstrapInfoResultClass UserStoreGetBootstrapInfoResultClass;

GType user_store_get_bootstrap_info_result_get_type (void);
#define TYPE_USER_STORE_GET_BOOTSTRAP_INFO_RESULT (user_store_get_bootstrap_info_result_get_type())
#define USER_STORE_GET_BOOTSTRAP_INFO_RESULT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_USER_STORE_GET_BOOTSTRAP_INFO_RESULT, UserStoreGetBootstrapInfoResult))
#define USER_STORE_GET_BOOTSTRAP_INFO_RESULT_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_USER_STORE_GET_BOOTSTRAP_INFO_RESULT, UserStoreGetBootstrapInfoResultClass))
#define IS_USER_STORE_GET_BOOTSTRAP_INFO_RESULT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_USER_STORE_GET_BOOTSTRAP_INFO_RESULT))
#define IS_USER_STORE_GET_BOOTSTRAP_INFO_RESULT_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_USER_STORE_GET_BOOTSTRAP_INFO_RESULT))
#define USER_STORE_GET_BOOTSTRAP_INFO_RESULT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_USER_STORE_GET_BOOTSTRAP_INFO_RESULT, UserStoreGetBootstrapInfoResultClass))

/* struct UserStoreAuthenticateLongSessionArgs */
struct _UserStoreAuthenticateLongSessionArgs
{ 
  ThriftStruct parent; 

  /* public */
  gchar * username;
  gboolean __isset_username;
  gchar * password;
  gboolean __isset_password;
  gchar * consumerKey;
  gboolean __isset_consumerKey;
  gchar * consumerSecret;
  gboolean __isset_consumerSecret;
  gchar * deviceIdentifier;
  gboolean __isset_deviceIdentifier;
  gchar * deviceDescription;
  gboolean __isset_deviceDescription;
  gboolean supportsTwoFactor;
  gboolean __isset_supportsTwoFactor;
};
typedef struct _UserStoreAuthenticateLongSessionArgs UserStoreAuthenticateLongSessionArgs;

struct _UserStoreAuthenticateLongSessionArgsClass
{
  ThriftStructClass parent;
};
typedef struct _UserStoreAuthenticateLongSessionArgsClass UserStoreAuthenticateLongSessionArgsClass;

GType user_store_authenticate_long_session_args_get_type (void);
#define TYPE_USER_STORE_AUTHENTICATE_LONG_SESSION_ARGS (user_store_authenticate_long_session_args_get_type())
#define USER_STORE_AUTHENTICATE_LONG_SESSION_ARGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_USER_STORE_AUTHENTICATE_LONG_SESSION_ARGS, UserStoreAuthenticateLongSessionArgs))
#define USER_STORE_AUTHENTICATE_LONG_SESSION_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_USER_STORE_AUTHENTICATE_LONG_SESSION_ARGS, UserStoreAuthenticateLongSessionArgsClass))
#define IS_USER_STORE_AUTHENTICATE_LONG_SESSION_ARGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_USER_STORE_AUTHENTICATE_LONG_SESSION_ARGS))
#define IS_USER_STORE_AUTHENTICATE_LONG_SESSION_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_USER_STORE_AUTHENTICATE_LONG_SESSION_ARGS))
#define USER_STORE_AUTHENTICATE_LONG_SESSION_ARGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_USER_STORE_AUTHENTICATE_LONG_SESSION_ARGS, UserStoreAuthenticateLongSessionArgsClass))

/* struct UserStoreAuthenticateLongSessionResult */
struct _UserStoreAuthenticateLongSessionResult
{ 
  ThriftStruct parent; 

  /* public */
  AuthenticationResult * success;
  gboolean __isset_success;
  EDAMUserException * userException;
  gboolean __isset_userException;
  EDAMSystemException * systemException;
  gboolean __isset_systemException;
};
typedef struct _UserStoreAuthenticateLongSessionResult UserStoreAuthenticateLongSessionResult;

struct _UserStoreAuthenticateLongSessionResultClass
{
  ThriftStructClass parent;
};
typedef struct _UserStoreAuthenticateLongSessionResultClass UserStoreAuthenticateLongSessionResultClass;

GType user_store_authenticate_long_session_result_get_type (void);
#define TYPE_USER_STORE_AUTHENTICATE_LONG_SESSION_RESULT (user_store_authenticate_long_session_result_get_type())
#define USER_STORE_AUTHENTICATE_LONG_SESSION_RESULT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_USER_STORE_AUTHENTICATE_LONG_SESSION_RESULT, UserStoreAuthenticateLongSessionResult))
#define USER_STORE_AUTHENTICATE_LONG_SESSION_RESULT_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_USER_STORE_AUTHENTICATE_LONG_SESSION_RESULT, UserStoreAuthenticateLongSessionResultClass))
#define IS_USER_STORE_AUTHENTICATE_LONG_SESSION_RESULT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_USER_STORE_AUTHENTICATE_LONG_SESSION_RESULT))
#define IS_USER_STORE_AUTHENTICATE_LONG_SESSION_RESULT_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_USER_STORE_AUTHENTICATE_LONG_SESSION_RESULT))
#define USER_STORE_AUTHENTICATE_LONG_SESSION_RESULT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_USER_STORE_AUTHENTICATE_LONG_SESSION_RESULT, UserStoreAuthenticateLongSessionResultClass))

/* struct UserStoreCompleteTwoFactorAuthenticationArgs */
struct _UserStoreCompleteTwoFactorAuthenticationArgs
{ 
  ThriftStruct parent; 

  /* public */
  gchar * authenticationToken;
  gboolean __isset_authenticationToken;
  gchar * oneTimeCode;
  gboolean __isset_oneTimeCode;
  gchar * deviceIdentifier;
  gboolean __isset_deviceIdentifier;
  gchar * deviceDescription;
  gboolean __isset_deviceDescription;
};
typedef struct _UserStoreCompleteTwoFactorAuthenticationArgs UserStoreCompleteTwoFactorAuthenticationArgs;

struct _UserStoreCompleteTwoFactorAuthenticationArgsClass
{
  ThriftStructClass parent;
};
typedef struct _UserStoreCompleteTwoFactorAuthenticationArgsClass UserStoreCompleteTwoFactorAuthenticationArgsClass;

GType user_store_complete_two_factor_authentication_args_get_type (void);
#define TYPE_USER_STORE_COMPLETE_TWO_FACTOR_AUTHENTICATION_ARGS (user_store_complete_two_factor_authentication_args_get_type())
#define USER_STORE_COMPLETE_TWO_FACTOR_AUTHENTICATION_ARGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_USER_STORE_COMPLETE_TWO_FACTOR_AUTHENTICATION_ARGS, UserStoreCompleteTwoFactorAuthenticationArgs))
#define USER_STORE_COMPLETE_TWO_FACTOR_AUTHENTICATION_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_USER_STORE_COMPLETE_TWO_FACTOR_AUTHENTICATION_ARGS, UserStoreCompleteTwoFactorAuthenticationArgsClass))
#define IS_USER_STORE_COMPLETE_TWO_FACTOR_AUTHENTICATION_ARGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_USER_STORE_COMPLETE_TWO_FACTOR_AUTHENTICATION_ARGS))
#define IS_USER_STORE_COMPLETE_TWO_FACTOR_AUTHENTICATION_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_USER_STORE_COMPLETE_TWO_FACTOR_AUTHENTICATION_ARGS))
#define USER_STORE_COMPLETE_TWO_FACTOR_AUTHENTICATION_ARGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_USER_STORE_COMPLETE_TWO_FACTOR_AUTHENTICATION_ARGS, UserStoreCompleteTwoFactorAuthenticationArgsClass))

/* struct UserStoreCompleteTwoFactorAuthenticationResult */
struct _UserStoreCompleteTwoFactorAuthenticationResult
{ 
  ThriftStruct parent; 

  /* public */
  AuthenticationResult * success;
  gboolean __isset_success;
  EDAMUserException * userException;
  gboolean __isset_userException;
  EDAMSystemException * systemException;
  gboolean __isset_systemException;
};
typedef struct _UserStoreCompleteTwoFactorAuthenticationResult UserStoreCompleteTwoFactorAuthenticationResult;

struct _UserStoreCompleteTwoFactorAuthenticationResultClass
{
  ThriftStructClass parent;
};
typedef struct _UserStoreCompleteTwoFactorAuthenticationResultClass UserStoreCompleteTwoFactorAuthenticationResultClass;

GType user_store_complete_two_factor_authentication_result_get_type (void);
#define TYPE_USER_STORE_COMPLETE_TWO_FACTOR_AUTHENTICATION_RESULT (user_store_complete_two_factor_authentication_result_get_type())
#define USER_STORE_COMPLETE_TWO_FACTOR_AUTHENTICATION_RESULT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_USER_STORE_COMPLETE_TWO_FACTOR_AUTHENTICATION_RESULT, UserStoreCompleteTwoFactorAuthenticationResult))
#define USER_STORE_COMPLETE_TWO_FACTOR_AUTHENTICATION_RESULT_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_USER_STORE_COMPLETE_TWO_FACTOR_AUTHENTICATION_RESULT, UserStoreCompleteTwoFactorAuthenticationResultClass))
#define IS_USER_STORE_COMPLETE_TWO_FACTOR_AUTHENTICATION_RESULT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_USER_STORE_COMPLETE_TWO_FACTOR_AUTHENTICATION_RESULT))
#define IS_USER_STORE_COMPLETE_TWO_FACTOR_AUTHENTICATION_RESULT_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_USER_STORE_COMPLETE_TWO_FACTOR_AUTHENTICATION_RESULT))
#define USER_STORE_COMPLETE_TWO_FACTOR_AUTHENTICATION_RESULT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_USER_STORE_COMPLETE_TWO_FACTOR_AUTHENTICATION_RESULT, UserStoreCompleteTwoFactorAuthenticationResultClass))

/* struct UserStoreRevokeLongSessionArgs */
struct _UserStoreRevokeLongSessionArgs
{ 
  ThriftStruct parent; 

  /* public */
  gchar * authenticationToken;
  gboolean __isset_authenticationToken;
};
typedef struct _UserStoreRevokeLongSessionArgs UserStoreRevokeLongSessionArgs;

struct _UserStoreRevokeLongSessionArgsClass
{
  ThriftStructClass parent;
};
typedef struct _UserStoreRevokeLongSessionArgsClass UserStoreRevokeLongSessionArgsClass;

GType user_store_revoke_long_session_args_get_type (void);
#define TYPE_USER_STORE_REVOKE_LONG_SESSION_ARGS (user_store_revoke_long_session_args_get_type())
#define USER_STORE_REVOKE_LONG_SESSION_ARGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_USER_STORE_REVOKE_LONG_SESSION_ARGS, UserStoreRevokeLongSessionArgs))
#define USER_STORE_REVOKE_LONG_SESSION_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_USER_STORE_REVOKE_LONG_SESSION_ARGS, UserStoreRevokeLongSessionArgsClass))
#define IS_USER_STORE_REVOKE_LONG_SESSION_ARGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_USER_STORE_REVOKE_LONG_SESSION_ARGS))
#define IS_USER_STORE_REVOKE_LONG_SESSION_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_USER_STORE_REVOKE_LONG_SESSION_ARGS))
#define USER_STORE_REVOKE_LONG_SESSION_ARGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_USER_STORE_REVOKE_LONG_SESSION_ARGS, UserStoreRevokeLongSessionArgsClass))

/* struct UserStoreRevokeLongSessionResult */
struct _UserStoreRevokeLongSessionResult
{ 
  ThriftStruct parent; 

  /* public */
  EDAMUserException * userException;
  gboolean __isset_userException;
  EDAMSystemException * systemException;
  gboolean __isset_systemException;
};
typedef struct _UserStoreRevokeLongSessionResult UserStoreRevokeLongSessionResult;

struct _UserStoreRevokeLongSessionResultClass
{
  ThriftStructClass parent;
};
typedef struct _UserStoreRevokeLongSessionResultClass UserStoreRevokeLongSessionResultClass;

GType user_store_revoke_long_session_result_get_type (void);
#define TYPE_USER_STORE_REVOKE_LONG_SESSION_RESULT (user_store_revoke_long_session_result_get_type())
#define USER_STORE_REVOKE_LONG_SESSION_RESULT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_USER_STORE_REVOKE_LONG_SESSION_RESULT, UserStoreRevokeLongSessionResult))
#define USER_STORE_REVOKE_LONG_SESSION_RESULT_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_USER_STORE_REVOKE_LONG_SESSION_RESULT, UserStoreRevokeLongSessionResultClass))
#define IS_USER_STORE_REVOKE_LONG_SESSION_RESULT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_USER_STORE_REVOKE_LONG_SESSION_RESULT))
#define IS_USER_STORE_REVOKE_LONG_SESSION_RESULT_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_USER_STORE_REVOKE_LONG_SESSION_RESULT))
#define USER_STORE_REVOKE_LONG_SESSION_RESULT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_USER_STORE_REVOKE_LONG_SESSION_RESULT, UserStoreRevokeLongSessionResultClass))

/* struct UserStoreAuthenticateToBusinessArgs */
struct _UserStoreAuthenticateToBusinessArgs
{ 
  ThriftStruct parent; 

  /* public */
  gchar * authenticationToken;
  gboolean __isset_authenticationToken;
};
typedef struct _UserStoreAuthenticateToBusinessArgs UserStoreAuthenticateToBusinessArgs;

struct _UserStoreAuthenticateToBusinessArgsClass
{
  ThriftStructClass parent;
};
typedef struct _UserStoreAuthenticateToBusinessArgsClass UserStoreAuthenticateToBusinessArgsClass;

GType user_store_authenticate_to_business_args_get_type (void);
#define TYPE_USER_STORE_AUTHENTICATE_TO_BUSINESS_ARGS (user_store_authenticate_to_business_args_get_type())
#define USER_STORE_AUTHENTICATE_TO_BUSINESS_ARGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_USER_STORE_AUTHENTICATE_TO_BUSINESS_ARGS, UserStoreAuthenticateToBusinessArgs))
#define USER_STORE_AUTHENTICATE_TO_BUSINESS_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_USER_STORE_AUTHENTICATE_TO_BUSINESS_ARGS, UserStoreAuthenticateToBusinessArgsClass))
#define IS_USER_STORE_AUTHENTICATE_TO_BUSINESS_ARGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_USER_STORE_AUTHENTICATE_TO_BUSINESS_ARGS))
#define IS_USER_STORE_AUTHENTICATE_TO_BUSINESS_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_USER_STORE_AUTHENTICATE_TO_BUSINESS_ARGS))
#define USER_STORE_AUTHENTICATE_TO_BUSINESS_ARGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_USER_STORE_AUTHENTICATE_TO_BUSINESS_ARGS, UserStoreAuthenticateToBusinessArgsClass))

/* struct UserStoreAuthenticateToBusinessResult */
struct _UserStoreAuthenticateToBusinessResult
{ 
  ThriftStruct parent; 

  /* public */
  AuthenticationResult * success;
  gboolean __isset_success;
  EDAMUserException * userException;
  gboolean __isset_userException;
  EDAMSystemException * systemException;
  gboolean __isset_systemException;
};
typedef struct _UserStoreAuthenticateToBusinessResult UserStoreAuthenticateToBusinessResult;

struct _UserStoreAuthenticateToBusinessResultClass
{
  ThriftStructClass parent;
};
typedef struct _UserStoreAuthenticateToBusinessResultClass UserStoreAuthenticateToBusinessResultClass;

GType user_store_authenticate_to_business_result_get_type (void);
#define TYPE_USER_STORE_AUTHENTICATE_TO_BUSINESS_RESULT (user_store_authenticate_to_business_result_get_type())
#define USER_STORE_AUTHENTICATE_TO_BUSINESS_RESULT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_USER_STORE_AUTHENTICATE_TO_BUSINESS_RESULT, UserStoreAuthenticateToBusinessResult))
#define USER_STORE_AUTHENTICATE_TO_BUSINESS_RESULT_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_USER_STORE_AUTHENTICATE_TO_BUSINESS_RESULT, UserStoreAuthenticateToBusinessResultClass))
#define IS_USER_STORE_AUTHENTICATE_TO_BUSINESS_RESULT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_USER_STORE_AUTHENTICATE_TO_BUSINESS_RESULT))
#define IS_USER_STORE_AUTHENTICATE_TO_BUSINESS_RESULT_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_USER_STORE_AUTHENTICATE_TO_BUSINESS_RESULT))
#define USER_STORE_AUTHENTICATE_TO_BUSINESS_RESULT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_USER_STORE_AUTHENTICATE_TO_BUSINESS_RESULT, UserStoreAuthenticateToBusinessResultClass))

/* struct UserStoreGetUserArgs */
struct _UserStoreGetUserArgs
{ 
  ThriftStruct parent; 

  /* public */
  gchar * authenticationToken;
  gboolean __isset_authenticationToken;
};
typedef struct _UserStoreGetUserArgs UserStoreGetUserArgs;

struct _UserStoreGetUserArgsClass
{
  ThriftStructClass parent;
};
typedef struct _UserStoreGetUserArgsClass UserStoreGetUserArgsClass;

GType user_store_get_user_args_get_type (void);
#define TYPE_USER_STORE_GET_USER_ARGS (user_store_get_user_args_get_type())
#define USER_STORE_GET_USER_ARGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_USER_STORE_GET_USER_ARGS, UserStoreGetUserArgs))
#define USER_STORE_GET_USER_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_USER_STORE_GET_USER_ARGS, UserStoreGetUserArgsClass))
#define IS_USER_STORE_GET_USER_ARGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_USER_STORE_GET_USER_ARGS))
#define IS_USER_STORE_GET_USER_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_USER_STORE_GET_USER_ARGS))
#define USER_STORE_GET_USER_ARGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_USER_STORE_GET_USER_ARGS, UserStoreGetUserArgsClass))

/* struct UserStoreGetUserResult */
struct _UserStoreGetUserResult
{ 
  ThriftStruct parent; 

  /* public */
  User * success;
  gboolean __isset_success;
  EDAMUserException * userException;
  gboolean __isset_userException;
  EDAMSystemException * systemException;
  gboolean __isset_systemException;
};
typedef struct _UserStoreGetUserResult UserStoreGetUserResult;

struct _UserStoreGetUserResultClass
{
  ThriftStructClass parent;
};
typedef struct _UserStoreGetUserResultClass UserStoreGetUserResultClass;

GType user_store_get_user_result_get_type (void);
#define TYPE_USER_STORE_GET_USER_RESULT (user_store_get_user_result_get_type())
#define USER_STORE_GET_USER_RESULT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_USER_STORE_GET_USER_RESULT, UserStoreGetUserResult))
#define USER_STORE_GET_USER_RESULT_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_USER_STORE_GET_USER_RESULT, UserStoreGetUserResultClass))
#define IS_USER_STORE_GET_USER_RESULT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_USER_STORE_GET_USER_RESULT))
#define IS_USER_STORE_GET_USER_RESULT_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_USER_STORE_GET_USER_RESULT))
#define USER_STORE_GET_USER_RESULT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_USER_STORE_GET_USER_RESULT, UserStoreGetUserResultClass))

/* struct UserStoreGetPublicUserInfoArgs */
struct _UserStoreGetPublicUserInfoArgs
{ 
  ThriftStruct parent; 

  /* public */
  gchar * username;
  gboolean __isset_username;
};
typedef struct _UserStoreGetPublicUserInfoArgs UserStoreGetPublicUserInfoArgs;

struct _UserStoreGetPublicUserInfoArgsClass
{
  ThriftStructClass parent;
};
typedef struct _UserStoreGetPublicUserInfoArgsClass UserStoreGetPublicUserInfoArgsClass;

GType user_store_get_public_user_info_args_get_type (void);
#define TYPE_USER_STORE_GET_PUBLIC_USER_INFO_ARGS (user_store_get_public_user_info_args_get_type())
#define USER_STORE_GET_PUBLIC_USER_INFO_ARGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_USER_STORE_GET_PUBLIC_USER_INFO_ARGS, UserStoreGetPublicUserInfoArgs))
#define USER_STORE_GET_PUBLIC_USER_INFO_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_USER_STORE_GET_PUBLIC_USER_INFO_ARGS, UserStoreGetPublicUserInfoArgsClass))
#define IS_USER_STORE_GET_PUBLIC_USER_INFO_ARGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_USER_STORE_GET_PUBLIC_USER_INFO_ARGS))
#define IS_USER_STORE_GET_PUBLIC_USER_INFO_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_USER_STORE_GET_PUBLIC_USER_INFO_ARGS))
#define USER_STORE_GET_PUBLIC_USER_INFO_ARGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_USER_STORE_GET_PUBLIC_USER_INFO_ARGS, UserStoreGetPublicUserInfoArgsClass))

/* struct UserStoreGetPublicUserInfoResult */
struct _UserStoreGetPublicUserInfoResult
{ 
  ThriftStruct parent; 

  /* public */
  PublicUserInfo * success;
  gboolean __isset_success;
  EDAMNotFoundException * notFoundException;
  gboolean __isset_notFoundException;
  EDAMSystemException * systemException;
  gboolean __isset_systemException;
  EDAMUserException * userException;
  gboolean __isset_userException;
};
typedef struct _UserStoreGetPublicUserInfoResult UserStoreGetPublicUserInfoResult;

struct _UserStoreGetPublicUserInfoResultClass
{
  ThriftStructClass parent;
};
typedef struct _UserStoreGetPublicUserInfoResultClass UserStoreGetPublicUserInfoResultClass;

GType user_store_get_public_user_info_result_get_type (void);
#define TYPE_USER_STORE_GET_PUBLIC_USER_INFO_RESULT (user_store_get_public_user_info_result_get_type())
#define USER_STORE_GET_PUBLIC_USER_INFO_RESULT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_USER_STORE_GET_PUBLIC_USER_INFO_RESULT, UserStoreGetPublicUserInfoResult))
#define USER_STORE_GET_PUBLIC_USER_INFO_RESULT_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_USER_STORE_GET_PUBLIC_USER_INFO_RESULT, UserStoreGetPublicUserInfoResultClass))
#define IS_USER_STORE_GET_PUBLIC_USER_INFO_RESULT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_USER_STORE_GET_PUBLIC_USER_INFO_RESULT))
#define IS_USER_STORE_GET_PUBLIC_USER_INFO_RESULT_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_USER_STORE_GET_PUBLIC_USER_INFO_RESULT))
#define USER_STORE_GET_PUBLIC_USER_INFO_RESULT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_USER_STORE_GET_PUBLIC_USER_INFO_RESULT, UserStoreGetPublicUserInfoResultClass))

/* struct UserStoreGetUserUrlsArgs */
struct _UserStoreGetUserUrlsArgs
{ 
  ThriftStruct parent; 

  /* public */
  gchar * authenticationToken;
  gboolean __isset_authenticationToken;
};
typedef struct _UserStoreGetUserUrlsArgs UserStoreGetUserUrlsArgs;

struct _UserStoreGetUserUrlsArgsClass
{
  ThriftStructClass parent;
};
typedef struct _UserStoreGetUserUrlsArgsClass UserStoreGetUserUrlsArgsClass;

GType user_store_get_user_urls_args_get_type (void);
#define TYPE_USER_STORE_GET_USER_URLS_ARGS (user_store_get_user_urls_args_get_type())
#define USER_STORE_GET_USER_URLS_ARGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_USER_STORE_GET_USER_URLS_ARGS, UserStoreGetUserUrlsArgs))
#define USER_STORE_GET_USER_URLS_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_USER_STORE_GET_USER_URLS_ARGS, UserStoreGetUserUrlsArgsClass))
#define IS_USER_STORE_GET_USER_URLS_ARGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_USER_STORE_GET_USER_URLS_ARGS))
#define IS_USER_STORE_GET_USER_URLS_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_USER_STORE_GET_USER_URLS_ARGS))
#define USER_STORE_GET_USER_URLS_ARGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_USER_STORE_GET_USER_URLS_ARGS, UserStoreGetUserUrlsArgsClass))

/* struct UserStoreGetUserUrlsResult */
struct _UserStoreGetUserUrlsResult
{ 
  ThriftStruct parent; 

  /* public */
  UserUrls * success;
  gboolean __isset_success;
  EDAMUserException * userException;
  gboolean __isset_userException;
  EDAMSystemException * systemException;
  gboolean __isset_systemException;
};
typedef struct _UserStoreGetUserUrlsResult UserStoreGetUserUrlsResult;

struct _UserStoreGetUserUrlsResultClass
{
  ThriftStructClass parent;
};
typedef struct _UserStoreGetUserUrlsResultClass UserStoreGetUserUrlsResultClass;

GType user_store_get_user_urls_result_get_type (void);
#define TYPE_USER_STORE_GET_USER_URLS_RESULT (user_store_get_user_urls_result_get_type())
#define USER_STORE_GET_USER_URLS_RESULT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_USER_STORE_GET_USER_URLS_RESULT, UserStoreGetUserUrlsResult))
#define USER_STORE_GET_USER_URLS_RESULT_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_USER_STORE_GET_USER_URLS_RESULT, UserStoreGetUserUrlsResultClass))
#define IS_USER_STORE_GET_USER_URLS_RESULT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_USER_STORE_GET_USER_URLS_RESULT))
#define IS_USER_STORE_GET_USER_URLS_RESULT_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_USER_STORE_GET_USER_URLS_RESULT))
#define USER_STORE_GET_USER_URLS_RESULT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_USER_STORE_GET_USER_URLS_RESULT, UserStoreGetUserUrlsResultClass))

/* struct UserStoreInviteToBusinessArgs */
struct _UserStoreInviteToBusinessArgs
{ 
  ThriftStruct parent; 

  /* public */
  gchar * authenticationToken;
  gboolean __isset_authenticationToken;
  gchar * emailAddress;
  gboolean __isset_emailAddress;
};
typedef struct _UserStoreInviteToBusinessArgs UserStoreInviteToBusinessArgs;

struct _UserStoreInviteToBusinessArgsClass
{
  ThriftStructClass parent;
};
typedef struct _UserStoreInviteToBusinessArgsClass UserStoreInviteToBusinessArgsClass;

GType user_store_invite_to_business_args_get_type (void);
#define TYPE_USER_STORE_INVITE_TO_BUSINESS_ARGS (user_store_invite_to_business_args_get_type())
#define USER_STORE_INVITE_TO_BUSINESS_ARGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_USER_STORE_INVITE_TO_BUSINESS_ARGS, UserStoreInviteToBusinessArgs))
#define USER_STORE_INVITE_TO_BUSINESS_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_USER_STORE_INVITE_TO_BUSINESS_ARGS, UserStoreInviteToBusinessArgsClass))
#define IS_USER_STORE_INVITE_TO_BUSINESS_ARGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_USER_STORE_INVITE_TO_BUSINESS_ARGS))
#define IS_USER_STORE_INVITE_TO_BUSINESS_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_USER_STORE_INVITE_TO_BUSINESS_ARGS))
#define USER_STORE_INVITE_TO_BUSINESS_ARGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_USER_STORE_INVITE_TO_BUSINESS_ARGS, UserStoreInviteToBusinessArgsClass))

/* struct UserStoreInviteToBusinessResult */
struct _UserStoreInviteToBusinessResult
{ 
  ThriftStruct parent; 

  /* public */
  EDAMUserException * userException;
  gboolean __isset_userException;
  EDAMSystemException * systemException;
  gboolean __isset_systemException;
};
typedef struct _UserStoreInviteToBusinessResult UserStoreInviteToBusinessResult;

struct _UserStoreInviteToBusinessResultClass
{
  ThriftStructClass parent;
};
typedef struct _UserStoreInviteToBusinessResultClass UserStoreInviteToBusinessResultClass;

GType user_store_invite_to_business_result_get_type (void);
#define TYPE_USER_STORE_INVITE_TO_BUSINESS_RESULT (user_store_invite_to_business_result_get_type())
#define USER_STORE_INVITE_TO_BUSINESS_RESULT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_USER_STORE_INVITE_TO_BUSINESS_RESULT, UserStoreInviteToBusinessResult))
#define USER_STORE_INVITE_TO_BUSINESS_RESULT_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_USER_STORE_INVITE_TO_BUSINESS_RESULT, UserStoreInviteToBusinessResultClass))
#define IS_USER_STORE_INVITE_TO_BUSINESS_RESULT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_USER_STORE_INVITE_TO_BUSINESS_RESULT))
#define IS_USER_STORE_INVITE_TO_BUSINESS_RESULT_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_USER_STORE_INVITE_TO_BUSINESS_RESULT))
#define USER_STORE_INVITE_TO_BUSINESS_RESULT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_USER_STORE_INVITE_TO_BUSINESS_RESULT, UserStoreInviteToBusinessResultClass))

/* struct UserStoreRemoveFromBusinessArgs */
struct _UserStoreRemoveFromBusinessArgs
{ 
  ThriftStruct parent; 

  /* public */
  gchar * authenticationToken;
  gboolean __isset_authenticationToken;
  gchar * emailAddress;
  gboolean __isset_emailAddress;
};
typedef struct _UserStoreRemoveFromBusinessArgs UserStoreRemoveFromBusinessArgs;

struct _UserStoreRemoveFromBusinessArgsClass
{
  ThriftStructClass parent;
};
typedef struct _UserStoreRemoveFromBusinessArgsClass UserStoreRemoveFromBusinessArgsClass;

GType user_store_remove_from_business_args_get_type (void);
#define TYPE_USER_STORE_REMOVE_FROM_BUSINESS_ARGS (user_store_remove_from_business_args_get_type())
#define USER_STORE_REMOVE_FROM_BUSINESS_ARGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_USER_STORE_REMOVE_FROM_BUSINESS_ARGS, UserStoreRemoveFromBusinessArgs))
#define USER_STORE_REMOVE_FROM_BUSINESS_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_USER_STORE_REMOVE_FROM_BUSINESS_ARGS, UserStoreRemoveFromBusinessArgsClass))
#define IS_USER_STORE_REMOVE_FROM_BUSINESS_ARGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_USER_STORE_REMOVE_FROM_BUSINESS_ARGS))
#define IS_USER_STORE_REMOVE_FROM_BUSINESS_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_USER_STORE_REMOVE_FROM_BUSINESS_ARGS))
#define USER_STORE_REMOVE_FROM_BUSINESS_ARGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_USER_STORE_REMOVE_FROM_BUSINESS_ARGS, UserStoreRemoveFromBusinessArgsClass))

/* struct UserStoreRemoveFromBusinessResult */
struct _UserStoreRemoveFromBusinessResult
{ 
  ThriftStruct parent; 

  /* public */
  EDAMUserException * userException;
  gboolean __isset_userException;
  EDAMSystemException * systemException;
  gboolean __isset_systemException;
  EDAMNotFoundException * notFoundException;
  gboolean __isset_notFoundException;
};
typedef struct _UserStoreRemoveFromBusinessResult UserStoreRemoveFromBusinessResult;

struct _UserStoreRemoveFromBusinessResultClass
{
  ThriftStructClass parent;
};
typedef struct _UserStoreRemoveFromBusinessResultClass UserStoreRemoveFromBusinessResultClass;

GType user_store_remove_from_business_result_get_type (void);
#define TYPE_USER_STORE_REMOVE_FROM_BUSINESS_RESULT (user_store_remove_from_business_result_get_type())
#define USER_STORE_REMOVE_FROM_BUSINESS_RESULT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_USER_STORE_REMOVE_FROM_BUSINESS_RESULT, UserStoreRemoveFromBusinessResult))
#define USER_STORE_REMOVE_FROM_BUSINESS_RESULT_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_USER_STORE_REMOVE_FROM_BUSINESS_RESULT, UserStoreRemoveFromBusinessResultClass))
#define IS_USER_STORE_REMOVE_FROM_BUSINESS_RESULT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_USER_STORE_REMOVE_FROM_BUSINESS_RESULT))
#define IS_USER_STORE_REMOVE_FROM_BUSINESS_RESULT_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_USER_STORE_REMOVE_FROM_BUSINESS_RESULT))
#define USER_STORE_REMOVE_FROM_BUSINESS_RESULT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_USER_STORE_REMOVE_FROM_BUSINESS_RESULT, UserStoreRemoveFromBusinessResultClass))

/* struct UserStoreUpdateBusinessUserIdentifierArgs */
struct _UserStoreUpdateBusinessUserIdentifierArgs
{ 
  ThriftStruct parent; 

  /* public */
  gchar * authenticationToken;
  gboolean __isset_authenticationToken;
  gchar * oldEmailAddress;
  gboolean __isset_oldEmailAddress;
  gchar * newEmailAddress;
  gboolean __isset_newEmailAddress;
};
typedef struct _UserStoreUpdateBusinessUserIdentifierArgs UserStoreUpdateBusinessUserIdentifierArgs;

struct _UserStoreUpdateBusinessUserIdentifierArgsClass
{
  ThriftStructClass parent;
};
typedef struct _UserStoreUpdateBusinessUserIdentifierArgsClass UserStoreUpdateBusinessUserIdentifierArgsClass;

GType user_store_update_business_user_identifier_args_get_type (void);
#define TYPE_USER_STORE_UPDATE_BUSINESS_USER_IDENTIFIER_ARGS (user_store_update_business_user_identifier_args_get_type())
#define USER_STORE_UPDATE_BUSINESS_USER_IDENTIFIER_ARGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_USER_STORE_UPDATE_BUSINESS_USER_IDENTIFIER_ARGS, UserStoreUpdateBusinessUserIdentifierArgs))
#define USER_STORE_UPDATE_BUSINESS_USER_IDENTIFIER_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_USER_STORE_UPDATE_BUSINESS_USER_IDENTIFIER_ARGS, UserStoreUpdateBusinessUserIdentifierArgsClass))
#define IS_USER_STORE_UPDATE_BUSINESS_USER_IDENTIFIER_ARGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_USER_STORE_UPDATE_BUSINESS_USER_IDENTIFIER_ARGS))
#define IS_USER_STORE_UPDATE_BUSINESS_USER_IDENTIFIER_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_USER_STORE_UPDATE_BUSINESS_USER_IDENTIFIER_ARGS))
#define USER_STORE_UPDATE_BUSINESS_USER_IDENTIFIER_ARGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_USER_STORE_UPDATE_BUSINESS_USER_IDENTIFIER_ARGS, UserStoreUpdateBusinessUserIdentifierArgsClass))

/* struct UserStoreUpdateBusinessUserIdentifierResult */
struct _UserStoreUpdateBusinessUserIdentifierResult
{ 
  ThriftStruct parent; 

  /* public */
  EDAMUserException * userException;
  gboolean __isset_userException;
  EDAMSystemException * systemException;
  gboolean __isset_systemException;
  EDAMNotFoundException * notFoundException;
  gboolean __isset_notFoundException;
};
typedef struct _UserStoreUpdateBusinessUserIdentifierResult UserStoreUpdateBusinessUserIdentifierResult;

struct _UserStoreUpdateBusinessUserIdentifierResultClass
{
  ThriftStructClass parent;
};
typedef struct _UserStoreUpdateBusinessUserIdentifierResultClass UserStoreUpdateBusinessUserIdentifierResultClass;

GType user_store_update_business_user_identifier_result_get_type (void);
#define TYPE_USER_STORE_UPDATE_BUSINESS_USER_IDENTIFIER_RESULT (user_store_update_business_user_identifier_result_get_type())
#define USER_STORE_UPDATE_BUSINESS_USER_IDENTIFIER_RESULT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_USER_STORE_UPDATE_BUSINESS_USER_IDENTIFIER_RESULT, UserStoreUpdateBusinessUserIdentifierResult))
#define USER_STORE_UPDATE_BUSINESS_USER_IDENTIFIER_RESULT_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_USER_STORE_UPDATE_BUSINESS_USER_IDENTIFIER_RESULT, UserStoreUpdateBusinessUserIdentifierResultClass))
#define IS_USER_STORE_UPDATE_BUSINESS_USER_IDENTIFIER_RESULT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_USER_STORE_UPDATE_BUSINESS_USER_IDENTIFIER_RESULT))
#define IS_USER_STORE_UPDATE_BUSINESS_USER_IDENTIFIER_RESULT_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_USER_STORE_UPDATE_BUSINESS_USER_IDENTIFIER_RESULT))
#define USER_STORE_UPDATE_BUSINESS_USER_IDENTIFIER_RESULT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_USER_STORE_UPDATE_BUSINESS_USER_IDENTIFIER_RESULT, UserStoreUpdateBusinessUserIdentifierResultClass))

/* struct UserStoreListBusinessUsersArgs */
struct _UserStoreListBusinessUsersArgs
{ 
  ThriftStruct parent; 

  /* public */
  gchar * authenticationToken;
  gboolean __isset_authenticationToken;
};
typedef struct _UserStoreListBusinessUsersArgs UserStoreListBusinessUsersArgs;

struct _UserStoreListBusinessUsersArgsClass
{
  ThriftStructClass parent;
};
typedef struct _UserStoreListBusinessUsersArgsClass UserStoreListBusinessUsersArgsClass;

GType user_store_list_business_users_args_get_type (void);
#define TYPE_USER_STORE_LIST_BUSINESS_USERS_ARGS (user_store_list_business_users_args_get_type())
#define USER_STORE_LIST_BUSINESS_USERS_ARGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_USER_STORE_LIST_BUSINESS_USERS_ARGS, UserStoreListBusinessUsersArgs))
#define USER_STORE_LIST_BUSINESS_USERS_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_USER_STORE_LIST_BUSINESS_USERS_ARGS, UserStoreListBusinessUsersArgsClass))
#define IS_USER_STORE_LIST_BUSINESS_USERS_ARGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_USER_STORE_LIST_BUSINESS_USERS_ARGS))
#define IS_USER_STORE_LIST_BUSINESS_USERS_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_USER_STORE_LIST_BUSINESS_USERS_ARGS))
#define USER_STORE_LIST_BUSINESS_USERS_ARGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_USER_STORE_LIST_BUSINESS_USERS_ARGS, UserStoreListBusinessUsersArgsClass))

/* struct UserStoreListBusinessUsersResult */
struct _UserStoreListBusinessUsersResult
{ 
  ThriftStruct parent; 

  /* public */
  GPtrArray * success;
  gboolean __isset_success;
  EDAMUserException * userException;
  gboolean __isset_userException;
  EDAMSystemException * systemException;
  gboolean __isset_systemException;
};
typedef struct _UserStoreListBusinessUsersResult UserStoreListBusinessUsersResult;

struct _UserStoreListBusinessUsersResultClass
{
  ThriftStructClass parent;
};
typedef struct _UserStoreListBusinessUsersResultClass UserStoreListBusinessUsersResultClass;

GType user_store_list_business_users_result_get_type (void);
#define TYPE_USER_STORE_LIST_BUSINESS_USERS_RESULT (user_store_list_business_users_result_get_type())
#define USER_STORE_LIST_BUSINESS_USERS_RESULT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_USER_STORE_LIST_BUSINESS_USERS_RESULT, UserStoreListBusinessUsersResult))
#define USER_STORE_LIST_BUSINESS_USERS_RESULT_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_USER_STORE_LIST_BUSINESS_USERS_RESULT, UserStoreListBusinessUsersResultClass))
#define IS_USER_STORE_LIST_BUSINESS_USERS_RESULT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_USER_STORE_LIST_BUSINESS_USERS_RESULT))
#define IS_USER_STORE_LIST_BUSINESS_USERS_RESULT_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_USER_STORE_LIST_BUSINESS_USERS_RESULT))
#define USER_STORE_LIST_BUSINESS_USERS_RESULT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_USER_STORE_LIST_BUSINESS_USERS_RESULT, UserStoreListBusinessUsersResultClass))

/* struct UserStoreListBusinessInvitationsArgs */
struct _UserStoreListBusinessInvitationsArgs
{ 
  ThriftStruct parent; 

  /* public */
  gchar * authenticationToken;
  gboolean __isset_authenticationToken;
  gboolean includeRequestedInvitations;
  gboolean __isset_includeRequestedInvitations;
};
typedef struct _UserStoreListBusinessInvitationsArgs UserStoreListBusinessInvitationsArgs;

struct _UserStoreListBusinessInvitationsArgsClass
{
  ThriftStructClass parent;
};
typedef struct _UserStoreListBusinessInvitationsArgsClass UserStoreListBusinessInvitationsArgsClass;

GType user_store_list_business_invitations_args_get_type (void);
#define TYPE_USER_STORE_LIST_BUSINESS_INVITATIONS_ARGS (user_store_list_business_invitations_args_get_type())
#define USER_STORE_LIST_BUSINESS_INVITATIONS_ARGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_USER_STORE_LIST_BUSINESS_INVITATIONS_ARGS, UserStoreListBusinessInvitationsArgs))
#define USER_STORE_LIST_BUSINESS_INVITATIONS_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_USER_STORE_LIST_BUSINESS_INVITATIONS_ARGS, UserStoreListBusinessInvitationsArgsClass))
#define IS_USER_STORE_LIST_BUSINESS_INVITATIONS_ARGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_USER_STORE_LIST_BUSINESS_INVITATIONS_ARGS))
#define IS_USER_STORE_LIST_BUSINESS_INVITATIONS_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_USER_STORE_LIST_BUSINESS_INVITATIONS_ARGS))
#define USER_STORE_LIST_BUSINESS_INVITATIONS_ARGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_USER_STORE_LIST_BUSINESS_INVITATIONS_ARGS, UserStoreListBusinessInvitationsArgsClass))

/* struct UserStoreListBusinessInvitationsResult */
struct _UserStoreListBusinessInvitationsResult
{ 
  ThriftStruct parent; 

  /* public */
  GPtrArray * success;
  gboolean __isset_success;
  EDAMUserException * userException;
  gboolean __isset_userException;
  EDAMSystemException * systemException;
  gboolean __isset_systemException;
};
typedef struct _UserStoreListBusinessInvitationsResult UserStoreListBusinessInvitationsResult;

struct _UserStoreListBusinessInvitationsResultClass
{
  ThriftStructClass parent;
};
typedef struct _UserStoreListBusinessInvitationsResultClass UserStoreListBusinessInvitationsResultClass;

GType user_store_list_business_invitations_result_get_type (void);
#define TYPE_USER_STORE_LIST_BUSINESS_INVITATIONS_RESULT (user_store_list_business_invitations_result_get_type())
#define USER_STORE_LIST_BUSINESS_INVITATIONS_RESULT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_USER_STORE_LIST_BUSINESS_INVITATIONS_RESULT, UserStoreListBusinessInvitationsResult))
#define USER_STORE_LIST_BUSINESS_INVITATIONS_RESULT_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_USER_STORE_LIST_BUSINESS_INVITATIONS_RESULT, UserStoreListBusinessInvitationsResultClass))
#define IS_USER_STORE_LIST_BUSINESS_INVITATIONS_RESULT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_USER_STORE_LIST_BUSINESS_INVITATIONS_RESULT))
#define IS_USER_STORE_LIST_BUSINESS_INVITATIONS_RESULT_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_USER_STORE_LIST_BUSINESS_INVITATIONS_RESULT))
#define USER_STORE_LIST_BUSINESS_INVITATIONS_RESULT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_USER_STORE_LIST_BUSINESS_INVITATIONS_RESULT, UserStoreListBusinessInvitationsResultClass))

/* struct UserStoreGetAccountLimitsArgs */
struct _UserStoreGetAccountLimitsArgs
{ 
  ThriftStruct parent; 

  /* public */
  ServiceLevel serviceLevel;
  gboolean __isset_serviceLevel;
};
typedef struct _UserStoreGetAccountLimitsArgs UserStoreGetAccountLimitsArgs;

struct _UserStoreGetAccountLimitsArgsClass
{
  ThriftStructClass parent;
};
typedef struct _UserStoreGetAccountLimitsArgsClass UserStoreGetAccountLimitsArgsClass;

GType user_store_get_account_limits_args_get_type (void);
#define TYPE_USER_STORE_GET_ACCOUNT_LIMITS_ARGS (user_store_get_account_limits_args_get_type())
#define USER_STORE_GET_ACCOUNT_LIMITS_ARGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_USER_STORE_GET_ACCOUNT_LIMITS_ARGS, UserStoreGetAccountLimitsArgs))
#define USER_STORE_GET_ACCOUNT_LIMITS_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_USER_STORE_GET_ACCOUNT_LIMITS_ARGS, UserStoreGetAccountLimitsArgsClass))
#define IS_USER_STORE_GET_ACCOUNT_LIMITS_ARGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_USER_STORE_GET_ACCOUNT_LIMITS_ARGS))
#define IS_USER_STORE_GET_ACCOUNT_LIMITS_ARGS_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_USER_STORE_GET_ACCOUNT_LIMITS_ARGS))
#define USER_STORE_GET_ACCOUNT_LIMITS_ARGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_USER_STORE_GET_ACCOUNT_LIMITS_ARGS, UserStoreGetAccountLimitsArgsClass))

/* struct UserStoreGetAccountLimitsResult */
struct _UserStoreGetAccountLimitsResult
{ 
  ThriftStruct parent; 

  /* public */
  AccountLimits * success;
  gboolean __isset_success;
  EDAMUserException * userException;
  gboolean __isset_userException;
};
typedef struct _UserStoreGetAccountLimitsResult UserStoreGetAccountLimitsResult;

struct _UserStoreGetAccountLimitsResultClass
{
  ThriftStructClass parent;
};
typedef struct _UserStoreGetAccountLimitsResultClass UserStoreGetAccountLimitsResultClass;

GType user_store_get_account_limits_result_get_type (void);
#define TYPE_USER_STORE_GET_ACCOUNT_LIMITS_RESULT (user_store_get_account_limits_result_get_type())
#define USER_STORE_GET_ACCOUNT_LIMITS_RESULT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_USER_STORE_GET_ACCOUNT_LIMITS_RESULT, UserStoreGetAccountLimitsResult))
#define USER_STORE_GET_ACCOUNT_LIMITS_RESULT_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), _TYPE_USER_STORE_GET_ACCOUNT_LIMITS_RESULT, UserStoreGetAccountLimitsResultClass))
#define IS_USER_STORE_GET_ACCOUNT_LIMITS_RESULT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_USER_STORE_GET_ACCOUNT_LIMITS_RESULT))
#define IS_USER_STORE_GET_ACCOUNT_LIMITS_RESULT_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), TYPE_USER_STORE_GET_ACCOUNT_LIMITS_RESULT))
#define USER_STORE_GET_ACCOUNT_LIMITS_RESULT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_USER_STORE_GET_ACCOUNT_LIMITS_RESULT, UserStoreGetAccountLimitsResultClass))

#endif /* USER_STORE_TYPES_H */
